env:
  MAVEN_ARGS: -B -V -ntp -e -Djansi.passthrough=true -Dstyle.color=always -Djacoco.skip=true
jobs:
  test_java:
    name: Java ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Java
      uses: oracle-actions/setup-java@v1
      with:
        release: ${{ matrix.java }}
        version: latest
        website: jdk.java.net
    - continue-on-error: true
      name: Test
      run: ./mvnw $MAVEN_ARGS verify
    strategy:
      fail-fast: false
      matrix:
        java:
        - 22
        - 23
name: Cross-Version
on:
  repository_dispatch:
    types: trigger-ga___cross-version.yml
