jobs:
  dependency_graph:
    name: Update
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: '21'
    - continue-on-error: true
      name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v4
name: Dependency Graph
on:
  repository_dispatch:
    types: trigger-ga___dependency-graph.yml
