env:
  MAVEN_ARGS: -B -V -ntp -e -Djansi.passthrough=true -Dstyle.color=always
jobs:
  javadoc:
    name: Javadoc
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: '21'
    - continue-on-error: true
      name: Generate Javadoc
      run: ./mvnw $MAVEN_ARGS -DskipTests package javadoc:javadoc
  sonar:
    if: github.repository == 'assertj/assertj' && github.event_name == 'push'
    name: Sonar code analysis
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: '21'
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      name: Test with Sonar
      run: './mvnw $MAVEN_ARGS verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.organization=assertj -Dsonar.projectKey=joel-costigliola_assertj-core

        '
  test_os:
    name: OS ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: '21'
    - continue-on-error: true
      name: Test
      run: ./mvnw $MAVEN_ARGS verify
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
name: CI
on:
  repository_dispatch:
    types: trigger-ga___main.yml
