env:
  MAVEN_ARGS: -B -V -ntp -e -Djansi.passthrough=true -Dstyle.color=always
jobs:
  store-pitest-feedback:
    if: github.event.pull_request.head.repo.full_name != github.repository
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout project
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: '21'
    - continue-on-error: true
      name: run pitest
      run: './mvnw $MAVEN_ARGS -Ppitest -Dfeatures="+GIT(from[HEAD~1]), +gitci" test

        '
    - continue-on-error: true
      name: aggregate files
      run: './mvnw $MAVEN_ARGS -f assertj-core/pom.xml -Ppitest pitest-git:aggregate

        '
    - continue-on-error: true
      name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: pitest
        path: target/assertj-core/pit-reports-ci/
name: Receive
on:
  repository_dispatch:
    types: trigger-ga___pitest-receive-pr.yml
