env:
  MAVEN_ARGS: -B -V -ntp -e -Djansi.passthrough=true -Dstyle.color=always
jobs:
  pitest-update-pr:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: debug
      uses: hmarr/debug-action@v3
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '21'
    - continue-on-error: true
      name: Download artifact
      uses: dawidd6/action-download-artifact@v3
      with:
        name: pitest
        path: target/pit-reports-ci
        workflow: ${{ github.event.workflow_run.workflow_id }}
        workflow_conclusion: success
    - continue-on-error: true
      name: update pull request
      run: './mvnw $MAVEN_ARGS -DrepoToken=${{ secrets.GITHUB_TOKEN }} com.groupcdg:pitest-github-maven-plugin:1.1.1:updatePR

        '
name: Comment on the pull request
on:
  repository_dispatch:
    types: trigger-ga___pitest-updated-pr.yml
