jobs:
  qodana:
    name: Scan
    permissions:
      checks: write
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - continue-on-error: true
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      name: Qodana Scan
      uses: JetBrains/qodana-action@v2023.3
name: Qodana
on:
  repository_dispatch:
    types: trigger-ga___qodana.yml
